name: shopingpriject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.6.1
  google_nav_bar: ^5.0.6
  dot_navigation_bar:
  badges: ^3.1.2
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  bloc: ^8.1.2
  http: ^1.1.2
  envied: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    
    - lib\assets\imges\img1.jpg
    - lib\assets\imges\img2.jpg
    - lib\assets\imges\img3.png
    - lib\assets\imges\img4.png
    - lib\assets\imges\img5.png
    - lib\assets\imges\img12.png
    - lib\assets\imges\img11.png

    
    
  fonts:
    - family: Unna
      fonts:
        - asset: lib\fonts\Unna-Bold.ttf
          weight: 700
        


